config/routes.rb
Multiauth::Application.routes.draw do
  root "home#index"
  devise_for :users

  get "/auth/:provider/callback" => "auth#create"
  delete "/auth/destroy/:provider" => 'auth#destroy', as: :destroy_connection

  

end

app/models/auth.rb
class Auth < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :auths
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_filter :authenticate_user!
  def create
    auth = request.env["omniauth.auth"]
    uid = auth["uid"]
    provider = auth["provider"]
    unless Auth.find_by_uid_and_provider(uid,provider)
      Auth.create(uid:uid, provider:provider, user_id:current_user.id)
    end
    redirect_to root_url
  end

  def destroy
    provider = params[:provider]
    auth = Auth.find_by_provider_and_user_id(provider,current_user.id)
    auth.destroy
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @providers = current_user.auths.pluck(:provider)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 multi auth
- if user_signed_in?
  %ul
    %li= link_to "ログアウト", destroy_user_session_path, method: :delete
    - if @providers.include? "twitter"
      %li
        twitterと接続済み
        = link_to "接続解除", destroy_connection_path(:twitter), method: :delete, data:{confirm:"Sure？"}
    - else
      %li= link_to "twitterと接続", "/auth/twitter"
    - if @providers.include? "github"
      %li
        githubと接続済み
        = link_to "接続解除", destroy_connection_path(:github), method: :delete, data:{confirm:"Sure？"}
    - else
      %li= link_to "githubと接続", "/auth/github"
    - if @providers.include? "hatena"
      %li
        hatenaと接続済み
        = link_to "接続解除", destroy_connection_path(:hatena), method: :delete, data:{confirm:"Sure？"}
    - else
      %li= link_to "hatenaと接続", "/auth/hatena"
- else
  %ul
    %li= link_to "ログイン", new_user_session_path
    %li= link_to "サインアップ", new_registration_path(:user)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Multiauth
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield